name: cla-check
on:
  # Only run on pull requests: not pushes
  pull_request:
    branches: [ "master", "release/**" ]

jobs:
  cla-check:
    runs-on: self-hosted
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v1
