name: MacOS sanity checks
on:
  # Only run on pull requests: not pushes
  pull_request:
    branches: ["master", "release/**"]

jobs:
  macos-sanity:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "1.14.x"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install squashfs from homebrew
        run: |
          brew install squashfs

      - name: Build sanity checks
        run: |
          ./mkversion.sh
          go build -tags nosecboot -o /tmp/snp ./cmd/snap

      - name: Runtime sanity checks
        run: |
          /tmp/snp download hello
          /tmp/snp version
          # TODO: homebrew appears to be broken, brew install of squashfs fails
          # and goes unnoticed by travis
          if command -v mksquashfs; then /tmp/snp pack tests/lib/snaps/test-snapd-tools/ /tmp ; fi
