name: Inclusive naming PR check
on: pull_request

jobs:
  inclusive-naming-check:
    name: Inclusive-naming-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: tj-actions/changed-files@v45.0.4
        id: files

      - name: woke
        uses: get-woke/woke-action-reviewdog@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          fail-on-error: true
          woke-args: ${{ steps.files.outputs.all_changed_files }}
