name: Build rpm package

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'A json list of tags to indicate which runner to use'
        required: true
        type: string
      system:
        description: 'The system, as known to spread, to build the rpm package for'
        required: true
        type: string
      pkg-dir:
        description: 'The name of the relevant folder in packaging directory'
        required: true
        type: string
      config:
        description: 'The name of the mock config file'
        required: true
        type: string

jobs:
  build-rpm:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Download vendor
      uses: actions/download-artifact@v6
      with:
        name: vendor-pkgs
        path: /tmp/pkg

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set Fedora tag for Docker image
      run: |
        echo "DOCKER_TAG=latest" >> $GITHUB_ENV
        if [ "${{ inputs.system }}" = "amazon-linux-2-64" ]; then
          echo "DOCKER_TAG=42" >> $GITHUB_ENV
        fi

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        load: true
        build-args: |
          TAG=${{ env.DOCKER_TAG }}
        file: tests/lib/packaging/fedora.dockerfile
        tags: mock-base:latest

    - name: Create cache key
      # Force a cache refresh once a week by using the year and week number as part of the cache key
      run: echo "CACHE_KEY=mock-cache-${{ inputs.system }}-$(date '+%Y-%U')" >> $GITHUB_ENV

    - name: Cache mock dependencies
      uses: actions/cache@v4
      with:
        path: /tmp/mock
        key: ${{ env.CACHE_KEY }}

    - name: Set version in spec
      run: |
        version=$(cat /tmp/pkg/version)
        sed -i -e "s/^Version:.*$/Version: $version/g" "packaging/${{ inputs.pkg-dir }}/snapd.spec"

    - name: Build rpm
      run: |
        chmod -R o+rw .
        mkdir -p /tmp/mock
        mkdir -p /tmp/builds
        chmod -R o+rw /tmp/builds
        docker run --privileged --rm \
          --mount type=bind,src=/tmp/mock,dst=/var/cache/mock \
          --mount type=bind,src=$(pwd),dst=/home/mockbuilder/snapd \
          --mount type=bind,src=/tmp/pkg,dst=/tmp/pkg \
          --mount type=bind,src=/tmp/builds,dst=/home/mockbuilder/builds \
          mock-base:latest \
          bash -c "
            cd /home/mockbuilder/snapd && \
            tests/lib/packaging/build-rpm-mock.sh \
              --pkg-dir ${{ inputs.pkg-dir }} \
              --vendor-tar-dir /tmp/pkg \
              --config-file /etc/mock/${{ inputs.config }}.cfg
          "
        mkdir /tmp/uploads
        sudo find /tmp/builds/* -type f \
          ! -name '*debug*' \
          ! -name '*.src.rpm' \
          -name '*.rpm' \
          -exec mv {} /tmp/uploads \;

    - name: upload packages
      uses: actions/upload-artifact@v5
      with:
        name: package-${{ inputs.system }}
        path: /tmp/uploads
